version: '0.1"

services:
    db:
      image: mongo:latest
      ports:
	- '27017:27017'

    backend:
      image: 
      ports:
        - '3030:3030'
      links:
        - db

    frontend:
      image: 
      ports:
        - '3000:3000'
